blank_issues_enabled: true
contact_links: [
  {
    name: "Get in touch with LMU Developers",
    url: "mailto:contact@lmu-dev.org",
    about: "Write us an email if you'd liek to get in contact with us.",
    category: "Support"
  }
]
issue_types:
  - name: Bug
    description: An unexpected problem or behavior
    labels: ["bug"]
  - name: Feature
    description: A request, idea, or new functionality
    labels: ["enhancement"]
  - name: Task
    description: A specific piece of work
    labels: ["task"]
